apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: node1-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.49.2/32
---
apiVersion: v1
kind: Service
metadata:
  name: test-uptime-kuma-d5q5ak3g
  annotations:
    metallb.io/address-pool: node1-pool
    metallb.io/allow-shared-ip: "node1"
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: test-uptime-kuma-d5q5ak3g
  type: LoadBalancer
